# Generated by Django 6.0.2 on 2026-02-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('store_name', models.CharField(max_length=200)),
                ('store_address', models.CharField(max_length=255)),
                ('store_city', models.CharField(max_length=100)),
                ('items', models.JSONField()),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('preferred_delivery_time', models.DateTimeField()),
                ('bidding_deadline', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('open', 'Open for Bids'), ('bidding_closed', 'Bidding Closed'), ('assigned', 'Shopper Assigned'), ('in_progress', 'Shopping in Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type__in': ['client', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_lists', to=settings.AUTH_USER_MODEL)),
                ('selected_shopper', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['shopper', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_structured', to='lists.shoppinglist')),
            ],
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['status'], name='lists_shopp_status_4590bf_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['client', 'status'], name='lists_shopp_client__f81a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['bidding_deadline'], name='lists_shopp_bidding_e165e2_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['store_city'], name='lists_shopp_store_c_8a4735_idx'),
        ),
    ]
