# Generated by Django 6.0.2 on 2026-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
