# Generated by Django 6.0.2 on 2026-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_sell_85c761_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_email_6f2530_idx',
            old_name='users_email_4b85f2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_phone_n_7fe504_idx',
            old_name='users_phone_n_a3b1c5_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_bid_distance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='total_lists_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('shopper', 'Shopper'), ('both', 'Both')], default='client', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['city', 'state'], name='users_user_city_23f94f_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
    ]
