# Generated by Django 6.0.2 on 2026-02-18 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('message', models.TextField(blank=True, max_length=500)),
                ('estimated_time', models.IntegerField(help_text='Estimated shopping time in minutes')),
                ('distance_to_store', models.DecimalField(decimal_places=2, help_text='Distance in miles/km', max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopper', models.ForeignKey(limit_choices_to={'user_type__in': ['shopper', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lists.shoppinglist')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bids.bid')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['shopping_list', 'status'], name='bids_bid_shoppin_d4873a_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['shopper', 'status'], name='bids_bid_shopper_18156a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('shopper', 'shopping_list')},
        ),
    ]
